### ISSUE TITLE
weak algorithms / security

### ISSUE THREAD

**Issue by DanielRuf** [WBCE/WBCE_CMS#273]
Please do not store passwords with md5 but password_*(hash) and password_compat, do not use *rand but random_int/bytes and random_compat, and some more things (did not hav so much time if typecasting, prepared statements, varaible filtering and so on are used).

**Comment by NorHei** [comment]
All good thougts!
Next Version will replace md5 whith password_hash () . Its already added in 2.0 . 

To be true , i did not know about "random_compat" and as we needed to keep 5.3 Supoort  we did not use 
random_int/bytes   as it was PHP 7 only.  We will add this ASAP !

**Comment by NorHei** [comment]
We need to take care of this issue in Installer and upgradescript

> Exception: "Could not gather sufficient random data"
> 
> If an Exception is thrown, then your operating system is not secure.
> 
> If you're on Windows, make sure you enable mcrypt.
> If you're on any other OS, make sure /dev/urandom is readable.
> FreeBSD jails need to expose /dev/urandom from the host OS
> If you use open_basedir, make sure /dev/urandom is allowed
> This library does not (and will not accept any patches to) fall back to an insecure random number generator.
>

**Comment by DanielRuf** [comment]
Bump.

**Comment by mrbaseman** [comment]
addressed by df2dd94481099a6052da1615a725d93b78ab62e5

**Comment by DanielRuf** [comment]
Better use `password-compat` instead of falling back to `md5` =)

**Comment by mrbaseman** [comment]
For existing installations the hashes are md5. So, we should support them in order to make a smooth transition. Each account that logs in after an update is converted to a better hash behind the curtains. For the encryption the fallback is intended for the migration of old installations. Several things won't work with php<5.5 and once php is updated the migration of the hashes starts in the background.
