### ISSUE TITLE
Cannot redeclare rm_full_dir() 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#281]
Fatal error: Cannot redeclare rm_full_dir() (previously declared in /.../framework/functions.php:31) in /.../framework/functions.php on line 68

Error appeared in Bakery (try to save item), but refers to functions.php

**Comment by webbird** [comment]
This happens if the functions.php is included more than once. Use require_once / include_once or wrap rm_full_dir() with function_exists().

**Comment by webbird** [comment]
LEPTON-solution: 

```
/**
 *  Define that this file has been loaded
 *
 *  To avoid double function-declarations (inside LEPTON) and to avoid a massiv use
 *  of "if(!function_exists('any_function_name_here_since_wb_2.5.0')) {" we've to place it
 *  inside this condition-body!
 *
 */
if (!defined('FUNCTIONS_FILE_LOADED'))
{
    define('FUNCTIONS_FILE_LOADED', true);

    ...functions here...
}
```

**Comment by Colinax** [comment]
It could be that this [change](https://github.com/WBCE/WBCE_CMS/commit/c181c68dc6c38592553ea176966ee296a4c6f0cb) causes the bug. 

Please remove this added line and check if Bakery works fine again.

**Comment by instantflorian** [comment]
Alright, that did the trick, but I guess the change happened with 
intention, so what will break if removing that line?

**Comment by cwsoft** [comment]
Guess not too much will break yet w/o loading functions file. Idea from Norhei was to include it by default as many core parts or older modules will include it. In 2.x it was done with lots of require -> require_once changes too. I wouldn't do it with a minor release, as it might need to force modules or core files to change some require statements. 

ZEN of Python: Explicit is better than implicit. If core or modules need the functions.php file, they should include it instead of loading it by default. At least in a minor release without backward incompatible changes.

**Comment by NorHei** [comment]
The problem is fixed in all files in bakery except one , all use require_once . 
I would guess that that author simply forgot to fix this one . 

I already contacted him. 

Including core files whithout thinking about that it can be already loaded by the core or maybe another module, is an old WB habit and a really bad one. Especially as the functions.php is needed almost everywhere...

**Comment by instantflorian** [comment]
I close this issue since it's merely a module thing (Bakery / OfA)
