### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by Tangol** [WBCE/WBCE_CMS#303]
I've installed WBCE 1.3 using English as the main language, but found translation issues all over the place.
![language](https://user-images.githubusercontent.com/3336728/32149029-80979de2-bd07-11e7-91ac-911f92d80ecd.png)

In my opinion, WBCE needs to be an **English** first CMS, as this is the default language for web apps.

**Comment by Colinax** [comment]
Hi Tangol,
i can confirm that the "zurück" (Back) Buttons are Translation Errors.

I check and fix it.

The next "4 Zeichen [26] Rest"  is a theme function and these words are not included in the language files of the CMS.
Due to the (old) theme-system, a translation is not easy to implement.

The third part shows a template feature, so it is in the makers decision which features and languages he supports
