### ISSUE TITLE
Empty referrer information in admin tool Visitor statistics

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#306]
See https://forum.wbce.org/viewtopic.php?pid=15052#p15052
The "original" module by Ruud seems to work better than the one which is included in WBCE CMS 1.3

**Comment by Colinax** [comment]
If I'm not wrong, the $referer in our 0.1.12 can not work.

I found the following text in the language files: To enable the recognition of references and search keys in WebsiteBaker versions 2.8.3 and higher, add the following line to config.php at the root of your website, just before the line: require_once (WB_PATH . \ '/ Framework / initialize. Php \');

The important thing is "just before the line", our solution in 0.1.12 inserts the code because of the order "shortly after".

**Comment by Colinax** [comment]
should be fixed with 1fbc2018ae7c940b23681eb41f319f93646d0771 and 27912d317917c6907dd0a87a370b8ce9110c6ebe
