### ISSUE TITLE
Some .htt placeholders not set in modify.php if blocks are disabled

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WBCE_CMS#322]
If **blocks** are **disabled** in general settings, some placeholders don't have assigned variables – leading to `{SOME_PLACEHOLDER}` output as seen in the attached screenshot.
![placeholders-not set](https://user-images.githubusercontent.com/2983578/35113748-db6b0532-fc82-11e7-966e-92d5e3cbfcda.png)

This issue arises because in `admin/pages/modify.php`, Line 163-169, the assignment took place inside a `if (SECTION_BLOCKS)` statement. So, if blocks are disabled, the corresponding placeholders will not be set. And because `$pageModifyTemplate->set_unknowns('keep');` is set in line 53, the placeholders are shown to the user.

To be honest: Until today I never ever worked on a site with disabled blocks. But i am currently updating an old WB 2.8.3 (wich wasn't managed by me) to WBCE 1.3.1, i stumbled over this issue.

**Comment by instantflorian** [comment]
can confirm, I stumbled upon this too.

**Comment by BerndJM** [comment]
Just stumpled on this too.
I think the easiest fix would be to delete the if statement, so the placeholders will be assigned independent from activated blocks.
Because, even if no blocks are defined in the template there is at least one "main block" where all the content goes to and all sections are assigned to this "main block".

Additional the section anchor also is defined inside this if statement, which IMHO makes no sense.
