### ISSUE TITLE
Performance issues in pagetree on voluminous websites

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#327]
On websites with a huge amount of single pages (500+), the loading of the pagetree takes a very long time and ends up in timeouts if max_execution_time is too restrictive. This happens although the options in JS Admin - remember open branch, drag&drop - are disabled already.

In the current case, see https://forum.wbce.org/viewtopic.php?id=1851, a loop the file /include/phplib/template.inc caused a timeout:

while (list($k, $v) = each($this->varvals)) {
      $varvals_quoted[$k] = preg_replace(array('/\\\\/', '/\$/'), array('\\\\\\\\', '\\\\$'), $v);
    }

So do we need this? Can this be replaced with a less time absorbing function?

**Comment by rjgamer** [comment]
Please test this solution: https://forum.wbce.org/viewtopic.php?pid=16023#p16023

**Comment by instantflorian** [comment]
Update: https://forum.wbce.org/viewtopic.php?pid=16039#p16039

**Comment by digitalbricks** [comment]
I would suggest to retrieve only the pages on the first level when the pagetree is opened an then to load children pages asynchronously when a parent page is clicked. In addition a session variable or a local storage entry could save the id of the last opened parent – so if the user goes back, the last opend branch of the pagetree is reloaded (would be necessary in order to reflect changes of page settings such as title and also is a win for the editor).

Just for the record: This is not my idea – the guys over at ProcessWire realized their pagetree with such asynchronous loading of sub pages and it works quite well.

**Comment by rjgamer** [comment]
This is without a 100% refactoring of the pagetree not possible and currently also not the problem. The problem is the slow and old template engine.
