### ISSUE TITLE
fix php deprecations 

### ISSUE THREAD

**Issue by Colinax** [WBCE/WBCE_CMS#455]
The following deprecations exist in these files:

**/framework/class.wb.php:** get_magic_quotes_gpc is deprecated
**/framework/DseTwo.php:** each is deprecated
**/include/pclzip/pclzip.lib.php:** get_magic_quotes_runtime is deprecated
**/install/helper_functions.php:** get_magic_quotes_gpc is deprecated
**/install/update.php:** each is deprecated

**Comment by Colinax** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in .../framework/functions-utf8.php

**Comment by mrbaseman** [comment]
should be fixed with the following commits:
https://github.com/WBCE/WBCE_CMS/commit/ce161e7b1910bda5971e777d5e02b88eea0b7023
https://github.com/WBCE/WBCE_CMS/commit/89a83379e92d661d0dc96f76f3ce69ab61aa8d7d
https://github.com/WBCE/WBCE_CMS/commit/eeba2bb7bbe4f2ed93452e16855af5faf56329c9
any other deprecated issues with latest php versions?
