### ISSUE TITLE
Account and Registration form Overrides not working

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#463]
Trying to build custom forms in the way which it is described here
https://github.com/WBCE/WBCE_CMS/blob/master/wbce/modules/tool_account_settings/templates/Template_Info_EN.txt

does not work. The custom forms are ignored. The only way to change the appearance of the form is to edit the files in the modules/tool_account_settings/templates folder.

**Comment by WebDesignWorx** [comment]
Right. I just corrected the instructions:
https://github.com/WBCE/WBCE_CMS/commit/ee67657a76472c4f68d8381307383065ad64db85

The reason why we need yet another directory is because with the same approach we can actually override the email_templates.
It's not mentioned anywhere as far as I can remember, but it could.
It goes like:
``
    [DEFAULT_TEMPLATE]
        └─ overrides
            └─ account
                └─ email_templates
                    └─ EN
                    └─ DE
``

**Comment by instantflorian** [comment]
Fixed with 9bcd21754937fbbb3d0a359f34d2b68a100935b1
