### ISSUE TITLE
Installation fails with mysql error on PHP 7.4 / MySQL 8

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#468]
Using installation wizzard of current master.
After clicking on install button, installation wizzard appears again, error message:

Error: e26b: /outputfilter_dashboard : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function, version, platform, author, license) VALUES ('outputfilter_dashboard', ' at line 1

**Comment by mrbaseman** [comment]
oh, this has been closed automatically. My understanding of this issue:
one of the commits for #455 has introduced a regression which has broken `strip_magic()` and I did the similar mistake in `opf_fetch_clean()`:
`if (get_magic_quotes_gpc() and ...) {` was never executed because `get_magic_quotes_gpc()` has always returned `FALSE`, and reducing the condition to the part next to `and` enables a code branch which had been suppressed so far.
I'm not sure if this quoting issue actually was causing the e26b error. Therefore, I'm reopening this issue.

**Comment by mrbaseman** [comment]
After a deeper investigation I believe that 4a4a55a probably doesn't fix this. The error message comes from [this call to](https://github.com/WBCE/WBCE_CMS/blob/4a4a55afe04594a78b324ba1996b2f58cc775316/wbce/framework/functions.php#L1262) `$database->insertRow()` which might happen to be the first one of this kind that the installer executes. It might be something with the PDO class or something more general with php 7.4 or mysql 8

**Comment by instantflorian** [comment]
You are right, it seems to be a PDO issue.
I should have been mentioned before that on that testing environement 
the database is NOT adressed with "localhost", but 
"dbXXX.databaseserver.yyy", maybe this causes the PDO issues?

And: Installing the current release version is possible. (There are also 
errors due to deprecated warnings and session already started warnings, 
but the installation is complete afterwards and seem to work after 
fixing the known issues with /admin/settings/index.php , 
/admin/pages/index.php and  /framework/frontend.functions.php).

Having a look into the database I discover that the tables of the PDO 
branch are not complete, e.g. all default module tables except the table 
for OPF Dashboard are missing.

**Comment by Colinax** [comment]
already fixed
