### ISSUE TITLE
XSS Vulnerability 

### ISSUE THREAD

**Issue by zxc7528064** [WBCE/WBCE_CMS#481]
Hi ~ I find a XSS Vulnerability (Stored)
Version : 1.4.3
Author : Noth(沈彧璿)
Step 1 : login system
Step 2 : Click the "Settings" icon on the left
![9](https://user-images.githubusercontent.com/45315211/83340000-e2980900-a305-11ea-876e-5e135a64f957.jpg)
Step 3 : Insert the XSS test grammar on the "Website Footer" on the right and save it.
PoC : "><img src=1 onerror=alert(document.cookie)> 
![10](https://user-images.githubusercontent.com/45315211/83340027-15420180-a306-11ea-8929-4617a6ca9b4e.jpg)
Step 4 :  Back to the front desk
![11](https://user-images.githubusercontent.com/45315211/83340039-3b67a180-a306-11ea-8ed5-214bfa48470a.jpg)

**Comment by instantflorian** [comment]
Thanks for your advice.
But in these fields you do not even need any tricks to execute JavaScript, since the input fields allow usual <script> parts.
This is in my eyes neither an issue nor a vulnerability. Website owners have to make sure that no  malicious users gain backend access and do not have any access to the settings page by using  secure passwords and setting restrictive group rights.

**Comment by zxc7528064** [comment]
@instantflorian  Someone gains permission because of some improper methods, which will pose a serious threat to the server. If this vulnerability is fixed, the severity of this threat will be reduced
