### ISSUE TITLE
Using prepared statements

### ISSUE THREAD

**Issue by Atlasfreak** [WBCE/WBCE_CMS#518]
To mitigate issues like this https://huntr.dev/bounties/c330dc0d-220a-4b15-b785-5face4cf6ef7/ in the future. I think we should rewrite the whole database class to use prepared statements. We would of course also need to rewrite all queries to also use them but over all this would greatly improve security and prevent sql injections. In my opinion it would also simplify interactions with the database as you do not need to worry about escaping the values yourself.
Personally I would suggest using PDO but there are also other libriaries that support this.

If I understand [this forum post](https://forum.wbce.org/viewtopic.php?id=653) correctly it was already planned 6 years ago and was actually finished. It was [published as a module](https://forum.wbce.org/viewtopic.php?id=1592). Although I would not make the distinction between query and prepared query, just have an optional parameter "values" that is passed as prepared values when given.

**Comment by WebDesignWorx** [comment]
We had a small exchange about this subject the other day in the internal forum.
Generally I find this an interesting objective, but there is no one who is really interested in implementing this feature.
What we would need is something that would work simultaneously with our current Database class, so we can use both, prepared statements and the old style queries as we do right now. This, because we are not able to change all queries all at once + there are just too many WBCE modules to take care of right away.

I am closing this issue for the time being. However, if someone has a great implementation and wants to share it with us, feel free to open this issue again. Best case scenario would be if you can provide code we can look at.

**Comment by Atlasfreak** [comment]
I also thought about this a bit and I am absolutely with you that there needs to be backwards compatibility optimally with a warning or notice that old queries are deprecated and should no longer be used if possible.
If have the time in the future I might look into this further and tinker a bit with a potentiel replacement that fulfills these criteria.

**Comment by webbird** [comment]
If you wish to use prepared statements, try

$database->DbHandle->prepare(...)

**Comment by WebDesignWorx** [comment]
> If you wish to use prepared statements, try
> 
> $database->DbHandle->prepare(...)

That's definitely a good starting hint.
Definitely not of the highest priority atm, but who knows, maybe we'll get there.
Best regards.
