### ISSUE TITLE
Move frontend account management to a module.

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#72]
Its as bad as the search construct , has no page id , breaks navigation , ugly to maintain ...

**Comment by NorHei** [comment]
Moving this to Milestone Later , as this is no real core isssue. And i Addres Module Issues after 1.2.x  Core is done.

**Comment by WebDesignWorx** [comment]
Since the `/account/` core area was [reworked completely](https://github.com/WBCE/WBCE_CMS/commit/bd2523800e5b7cce71ff28c69c0f5a27fe34c40e), I wonder if this still is an issue?

What is the actual issue with `page_id 0`? And how does the `/account/` area negatively affect the navigations?
I'd like to learn so the issues may be considered in a follow up development of the `/account/` area.
